# Generated by Django 6.0.1 on 2026-01-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('astrologer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KundaliOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('tob', models.TimeField()),
                ('pob', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('astrologer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
