# Generated by Django 6.0.1 on 2026-01-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationorder',
            name='payment_status',
            field=models.CharField(default='PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='consultationorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consultationorder',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consultationorder',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultationorder',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
