# Generated by Django 6.0.1 on 2026-01-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consultationorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationorder',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consultationorder',
            name='payment_id',
            field=models.CharField(default='OLD_DATA', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationorder',
            name='razorpay_order_id',
            field=models.CharField(default='OLD_DATA', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultationorder',
            name='razorpay_signature',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
