# Generated by Django 6.0.1 on 2026-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_consultationorder_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KundaliRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('tob', models.TimeField()),
                ('pob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Free Kundali Request',
                'verbose_name_plural': 'Free Kundali Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='KundaliOrder',
        ),
        migrations.AlterModelOptions(
            name='consultationorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Paid Consultation', 'verbose_name_plural': 'Paid Consultations'},
        ),
        migrations.RenameField(
            model_name='consultationorder',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.AlterField(
            model_name='consultationorder',
            name='amount',
            field=models.IntegerField(help_text='Amount in INR'),
        ),
        migrations.AlterField(
            model_name='consultationorder',
            name='payment_status',
            field=models.CharField(default='PAID', help_text='PAID / FAILED', max_length=20),
        ),
    ]
