# Generated by Django 6.0.1 on 2026-01-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kundalirequest_delete_kundaliorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationorder',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationorder',
            name='pob',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultationorder',
            name='tob',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
